apiVersion: cache.x1kun.com/v1
kind: SimpleCache
metadata:
  labels:
    app.kubernetes.io/name: simplecache-operator
    app.kubernetes.io/managed-by: kustomize
  name: simplecache-sample
spec:
  size: 3
  image: simplecache:dev
  cacheBytes: 67108864
  ttlSeconds: 60
